const languageMap: { [key: string]: string } = {
  English: "EN",
  Swedish: "SV",
  Turkish: "TR",
  French: "FR",
  German: "DE",
  Spanish: "ES",
  Dutch: "NL",
  Italian: "IT",
  Polish: "PL",
  Ukrainian: "UK",
  Danish: "DA",
  Finnish: "FI",
  Norwegian: "NB",
  Russian: "RU",
  Chinese: "ZH",
  Japanese: "JA",
  Korean: "KO",
  Arabic: "AR",
  Portuguese: "PT",
  Greek: "EL",
  Czech: "CS",
  Hungarian: "HU",
  Romanian: "RO",
  Slovenian: "SL",
  Lithuanian: "LT",
  Estonian: "ET",
  Latvian: "LV",
  Bulgarian: "BG",
  Slovak: "SK",
  Indonesian: "ID",
  Malay: "MS",
  Hebrew: "HE",
  Vietnamese: "VI",
  Hindi: "HI",
  Thai: "TH",
 
};

export default languageMap;
